[tool.black]
line-length = 100
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | migrations
    | legacy
  )/
)
'''

[tool.isort]
py_version=310
profile = "black"
skip_glob = ["legacy/*", "migrations/*"]

[tool.pytest.ini_options]
python_functions = "test_*"
testpaths = [
    "tests"
]
